sampletikcetdata:
  target: athena
  outputs:
    athena:
      database: AwsDataCatalog
      region_name: us-west-2
      # s3_data_dir: s3://sample-snapshot-bucket/
      s3_data_dir: "{{ env_var('S3_BUCKET') }}" 
      s3_staging_dir: "{{ env_var('S3_ATHENA_LOG_BUCKET') }}" 
      threads: 1
      type: athena
      workgroup: athenaWorkGroup
      schema: sample_ticket_database
      aws_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}" 
      aws_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}" 
